title:              Jalbin Blog
email:              wlsdn13077@naver.com
description:        DevBlog
author:             Jalbin
baseurl:            "/blog"
url:                "https://jalbin1307.github.io"

# Social Profiles
#twitter_username:   SBootstrap
github_username:    Jalbin1307
facebook_username:  jalbin1307
instagram_username:  10._.gosu
# linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
